In [72]:
import numpy as np 
import pandas as pd

In [99]:
df=pd.read_csv("Iris.csv")
df.head()

ID  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [100]:
sizes = df['Species'].value_counts(sort = 1)
print(sizes)

Iris-setosa        50
Iris-virginica     50
Iris-versicolor    50
Name: Species, dtype: int64


In [101]:
df.drop(['ID'], axis=1, inplace=True)
df.head(2)

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa

In [102]:
df.Species[df.Species == 'Iris-versicolor'] = 1
df.Species[df.Species == 'Iris-virginica'] = 2
df.Species[df.Species == 'Iris-setosa'] = 3


<ipython-input-102-4f5c56acaf2a>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.Species[df.Species == 'Iris-versicolor'] = 1
<ipython-input-102-4f5c56acaf2a>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.Species[df.Species == 'Iris-virginica'] = 2
<ipython-input-102-4f5c56acaf2a>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.Species[df.Species == 'Iris-setosa'] = 3


In [103]:
print(df.head(100))


    SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm Species
0             5.1           3.5            1.4           0.2       3
1             4.9           3.0            1.4           0.2       3
2             4.7           3.2            1.3           0.2       3
3             4.6           3.1            1.5           0.2       3
4             5.0           3.6            1.4           0.2       3
..            ...           ...            ...           ...     ...
95            5.7           3.0            4.2           1.2       1
96            5.7           2.9            4.2           1.3       1
97            6.2           2.9            4.3           1.3       1
98            5.1           2.5            3.0           1.1       1
99            5.7           2.8            4.1           1.3       1

[100 rows x 5 columns]


In [104]:
Y = df["Species"].values

In [105]:
print(Y)

[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [106]:
df.dtypes

SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object

In [107]:
Y=Y.astype('int')

In [108]:
X = df.drop(labels = ["Species"], axis=1)  

In [114]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.20, random_state=1)

In [115]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [116]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [117]:
y_predict=classifier.predict(X_test)

In [118]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_predict))
print(classification_report(y_test, y_predict))

[[12  1  0]
 [ 0  6  0]
 [ 0  0 11]]
              precision    recall  f1-score   support

           1       1.00      0.92      0.96        13
           2       0.86      1.00      0.92         6
           3       1.00      1.00      1.00        11

    accuracy                           0.97        30
   macro avg       0.95      0.97      0.96        30
weighted avg       0.97      0.97      0.97        30

